### ISSUE TITLE
Disable HTML minification?

### ISSUE THREAD

**Issue by MarkLunney** [jdcrensh/create-react-app#18]
I'm using the 'no-minify' plugin for disabling CSS and JavaScript, but I also have a need to disable the minification of the index.html file which is generated by HtmlWebpackPlugin.

It looks like the PROD build passes a number of minify options to this plugin:

https://github.com/jdcrensh/create-react-app/blob/jdcrensh/packages/react-scripts/config/webpack.config.prod.js#L275

Would it be within the scope of this plugin to disable this too?

**Comment by jdcrensh** [comment]
I like this idea! But I think it might be better suited as its own plugin. The new plugin would give you a place to reconfigure options sent to `HtmlWebpackPlugin`. I may have to make an enhancement to enable plugin configuration via `cra.config.js`. How does that sound?

**Comment by MarkLunney** [comment]
Sounds like a good idea to make a separate plugin, as there are other HtmlWebpackPlugin options that may useful to override (full list on the [HTMLWebpackPlugin](https://github.com/jantimon/html-webpack-plugin) repo).

Really like the approach of this fork by the way, I appreciate the ideology behind Create React App but I often wish there were more escape hatches without ejecting, especially where plugins are concerned.
