### ISSUE TITLE
All plugins stop working in 3.4.2-0 

### ISSUE THREAD

**Issue by Andrei-Salanovich-epam** [jdcrensh/create-react-app#22]
Hello

I've updated the package to the latest version 3.4.2-0 and found that plugins just had stopped working.
It seems that the problem in the absence of  **configPath** in react-scripts/config/path.js, so no cra.config.js is being read anymore and no plugin is being applied.

**Comment by jdcrensh** [comment]
I did not realize the upgrade broke that. Will look into it as soon as I'm able.

**Comment by jdcrensh** [comment]
Released fix in 3.4.2-1
